app-set:
  categories:
    - 17010

channels:
  list:
    iphone-sales:
      enabled: true
    top-phone-offers:
      enabled: true
    smartphones-for-spare-parts:
      enabled: true
  settings:
    bots-channels-map:
      KufarSpy:
        - -1002312425178
publish:
  delays:
    channelsDelay:
      -1002367745711: 5
      -1002385506241: 0
