app-set:
  categories:
    - 17010

bots:
  associations:
      KufarSpy:
        - -1002312425178
channels:
  list:
    smartphones-for-spare-parts:
      enabled: true
  settings:
    publish:
      delays:
        -1002385506241: 0
  
