app-set:
  categories:
    - 17010

bots:
  associations:
      KufarSpy:
        - -1003858197006
channels:
  list:
    smartphones-for-spare-parts:
      enabled: true
  settings:
    publish:
      delays:
        -1003858197006: 0

test:
  property1: okay
  
